name: 'GoCICa'
description: 'Official GoCICa action for installing and setup GoCICa'
author: 'GoCICa'
inputs:
  version:
    description: |
      The version of golangci-lint to use.
      If not specified, the latest version will be used.
    required: false
runs:
  using: 'node20'
  main: 'dist/index.mjs'
