name: 'GoCICa Setup'
description: 'Official GoCICa action for installing and setup GoCICa'
author: 'GoCICa'
branding:
  icon: 'battery-charging'
  color: 'blue'
inputs:
  version:
    description: |
      The version of GoCICa to use.
      If not specified, the latest version will be used.
    required: false
    default: 'v0.1.0-alpha10'
  dir:
    description: 'Directory to store cache files'
    required: false
  log-level:
    description: 'Log level'
    required: false
    default: 'info'
runs:
  using: 'node20'
  main: 'dist/index.mjs'
