name: 'GoCICa'
description: 'Official GoCICa action for installing and setup GoCICa'
author: 'GoCICa'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'
