name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  gocica_run:
    name: A job to run GoCICa action
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04-arm
          - macos-latest
          - windows-latest
        version:
          - ""
          - "v0.1.0-alpha6"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache: false
      - name: GoCICa action
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Build standard library
        run: go install std
