on: [push]

jobs:
  gocica_run:
    name: A job to run GoCICa action
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04-arm
          - macos-latest
          - windows-latest
        version:
          - ""
          - "latest"
          - "v0.1.0-alpha2"
        remote:
          - "github"
          - "s3"
          - "none"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache: false
      - name: GoCICa action
        uses: ./
        with:
          version: ${{ matrix.version }}
          s3-region: ${{ secrets.S3_REGION }}
          s3-bucket: ${{ secrets.S3_BUCKET }}
          s3-access-key: ${{ secrets.S3_ACCESS_KEY }}
          s3-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      - name: Build standard library
        run: go install std
