on: [push]

jobs:
  gocica_run:
    runs-on: ubuntu-latest
    name: A job to run GoCICa action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GoCICa action
        uses: ./
